### ISSUE TITLE
Can not run app on real jailbroken device

### ISSUE THREAD

**Issue by karmamaster** [CharlieWhile13/ExampleXcodeApp#1]
Hello,
I have make my basic xcode project (create new one by xcode 11.7) using this method! It is running well on simulator but can not run on real device, it is crashing when we launch it! (iphone 6s. jailbroken, 14.4.1)

Do you have any clue to solve this?

Thanks

**Comment by elihwyma** [comment]
Ok so first things first, does the app show on Home Screen/App Library, and then pressing on it just crashes instantly?

If so, can I ask you to check the entitlements on the app by running `ldid -e /Applications/app.app/app`, obviously substituting in the name of your app.

**Comment by karmamaster** [comment]
> 
> 
> Ok so first things first, does the app show on Home Screen/App Library, and then pressing on it just crashes instantly?
> 
> If so, can I ask you to check the entitlements on the app by running `ldid -e /Applications/app.app/app`, obviously substituting in the name of your app.

yeah it is showing on the screen! but crashes instantly after launch screen :(
I have ran the command `ldid -e /Applications/app.app/app` and its returned my entitlements content as I defined like this

```
<plist version="1.0">
    <dict>
        <key>platform-application</key>
        <true/>
        <key>com.apple.private.skip-library-validation</key>
        <true/>
        <key>get-task-allow</key>
        <true/>
        <key>com.apple.private.security.no-container</key>
        <true/>
        <key>com.apple.security.iokit-user-client-class</key>
        <array>
            <string>IOUserClient</string>
        </array>
    </dict>
</plist>
```

**Comment by elihwyma** [comment]
Does the app work if you run it from Xcode normally

**Comment by karmamaster** [comment]
> 
> 
> Does the app work if you run it from Xcode normally

the app work normally in simulator, I don't know for some reasons that I can't login to my apple account so can not build as usual project, just build by make file

**Comment by elihwyma** [comment]
All I can suggest now is use Console and filter by the name of your app. Generally you'll get an error that will tell you what you're missing

**Comment by karmamaster** [comment]
Its dont show anything, just: killed: signal 9.  :(

**Comment by elihwyma** [comment]
I meant Console.app on your Mac
