### ISSUE TITLE
Final package Theos error

### ISSUE THREAD

**Issue by hansthirtytwo** [CharlieWhile13/ExampleXcodeApp#3]
When I try to run `make package FINALPACKAGE=1` it will send an error saying that the InstallationBuildProductLocation couldn’t move to my app because it might be deleted or doesn’t exist.

**Comment by elihwyma** [comment]
Are you by any chance using Xcode 14.3?

**Comment by hansthirtytwo** [comment]
yea

**Comment by elihwyma** [comment]
It's a bug I've encountered too. Specifically it seems that Apple have changed the naming scheme of release builds in 14.3 which is just wonderful. 

A temporary solution would be to use Xcode 14.2 for the time being. It might be worth cross posting this issue on the Theos GitHub.

**Comment by hansthirtytwo** [comment]
but is there any other way like renaming the scheme or something because my phone is using palera1n nightly on 16.4.1 and the sdk of Xcode 14.2 is only iOS 16.2.. or do I need to just download Xcode 14.2.

**Comment by elihwyma** [comment]
It doesn't matter what version of the SDK you use, it will still build and run fine on your device.

**Comment by hansthirtytwo** [comment]
alright..

**Comment by hansthirtytwo** [comment]
It worked thanks! so do I close
