### ISSUE TITLE
How do I add NSTask or posix_spawn?

### ISSUE THREAD

**Issue by hansthirtytwo** [CharlieWhile13/ExampleXcodeApp#4]
When I add NSTask or posix_spawn, there is always an error when building the app on Xcode, not on these, and also I added the `<key>get-task-allow</key><true/>` in the entitlements xml. So how do I add NSTask or posix_spawn w/o any errors.

**Comment by elihwyma** [comment]
Could you possibly say what error you get?

**Comment by hansthirtytwo** [comment]
It was something like `Cannot find scope “NSTask”` or  `Cannot find “NSTask” in scope`, but the posix_spawn, I use ChatGPT for that since idk how to use it, but there will always be an error about like Strings, etc.

**Comment by elihwyma** [comment]
I recommend using posix_spawn, use [this](https://github.com/Sileo/Sileo/blob/18e0ac2c90e8658ed9b787dca25a4c7c34edf93a/Sileo/Backend/Root%20Wrapper/RootWrapper.swift#L119) as a reference. You will need to declare some functions in the bridging header.

**Comment by hansthirtytwo** [comment]
Alr thanks

**Comment by hansthirtytwo** [comment]
I unfortunately cannot add the function, since there's lots of errors about "Cannot find 'CommandPath' in scope"

**Comment by elihwyma** [comment]
Please use a tiny bit of intuition and scroll down in the file to find the CommandPath class

**Comment by NotHansCYDIa** [comment]
I did that, but when I copy the code of the Bootstrap.swift file, there's an error w/ the .exists not being a scope of URL().

**Comment by hansthirtytwo** [comment]
nvm I imported & used NSTask then it worked and also thanks for the help!
